export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_USER = "LOGIN USER";

export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SUCCESS_MESSAGE = "ALERT_SUCCESS";
export const ERROR_MESSAGE = "ALERT_ERROR";

export const CREATE_BOOKING = "CREATE_BOOKING";
export const RETRIEVE_BOOKINGS = "RETRIEVE_BOOKINGS";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const DELETE_ALL_BOOKINGS = "DELETE_ALL_BOOKINGS";

export const CREATE_BLOG = "CREATE_BLOG";
export const RETRIEVE_BLOGS = "RETRIEVE_BLOGS";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_ALL_BLOGS = "DELETE_ALL_BLOGS";

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER = 'SET_USER';
export const USER_SET_DETAILS = 'USER_SET_DETAILS';

