export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SUCCESS_MESSAGE = "ALERT_SUCCESS";
export const ERROR_MESSAGE = "ALERT_ERROR";
export const ALERT_CLEAR = "CLEAR_ERROR";

export const USER_GETALL_REQUEST = "GETALL_REQUEST";
export const USER_GETALL_SUCCESS = "GETALL_SUCCESS";
export const USER_GETALL_FAILURE = "GETALL_FAILURE";

export const USER_DELETE_REQUEST = "DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "DELETE_FAILURE";