const BlogData = [
    {
      id: 1,
      image: "https://scontent-lga3-2.xx.fbcdn.net/v/t39.30808-6/333459502_1315738459006941_7139641215938873232_n.jpg?stp=dst-jpg_p720x720&_nc_cat=111&ccb=1-7&_nc_sid=730e14&_nc_ohc=aHeDqCtSZCYAX93QAQ6&_nc_ht=scontent-lga3-2.xx&edm=ALdPpPkEAAAA&oh=00_AfAbn9vkynsP2WqSrOghGmiBIvhfw0qFanVVd7lKIXG7fQ&oe=6412A16E",
      date: "March 10, 2023",
      title_one: "National Women & Girls Hiv/Aids Awareness Day",
      desc_one: "March 10 is National Women and Girls HIV/AIDS Awareness Day, a day to raise awareness about the impact of HIV on women and show support for women and girls with HIV..",
      title_two: "Nobis eleifend option conguenes.",
      desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros, sed posuere massa nunc quis dui. Integer ornare varius mi, in vehicula orci scelerisque sed. Fusce a massa nisi. Curabitur sit amet suscipit nisl. Sed eget nisl laoreet, suscipit enim nec, viverra eros. Nunc imperdiet risus leo, in rutrum erat dignissim id. Ut rhoncus vestibulum facilisis. Duis et lorem vitae ligula cursus venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae nisi tortor. Morbi leo nulla, posuere vel lectus a, egestas posuere lacus. Fusce eleifend hendrerit bibendum. Morbi nec efficitur ex.",
      title_three: "Mauris tempor, orci id pellentesque.",
      desc_three: "Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent fringilla dapibus dignissim. Pellentesque quis quam enim. Vestibulum ultrices, leo id suscipit efficitur, odio lorem rhoncus dolor, a facilisis neque mi ut ex. Quisque tempor urna a nisi pretium, a pretium massa tristique. Nullam in aliquam diam. Maecenas at nibh gravida, ornare eros non, commodo ligula. Sed efficitur sollicitudin auctor. Quisque nec imperdiet purus, in ornare odio. Quisque odio felis, vestibulum et.",
    },
    {
      id: 2,
      image: "./image/blog-02.jpg",
      date: "28 April, 2021",
      title_one: "International Women’s Day",
      desc_one: "Nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum.",
      title_two: "Nobis eleifend option conguenes.",
      desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros, sed posuere massa nunc quis dui. Integer ornare varius mi, in vehicula orci scelerisque sed. Fusce a massa nisi. Curabitur sit amet suscipit nisl. Sed eget nisl laoreet, suscipit enim nec, viverra eros. Nunc imperdiet risus leo, in rutrum erat dignissim id. Ut rhoncus vestibulum facilisis. Duis et lorem vitae ligula cursus venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae nisi tortor. Morbi leo nulla, posuere vel lectus a, egestas posuere lacus. Fusce eleifend hendrerit bibendum. Morbi nec efficitur ex.",
      title_three: "Mauris tempor, orci id pellentesque.",
      desc_three: "Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent fringilla dapibus dignissim. Pellentesque quis quam enim. Vestibulum ultrices, leo id suscipit efficitur, odio lorem rhoncus dolor, a facilisis neque mi ut ex. Quisque tempor urna a nisi pretium, a pretium massa tristique. Nullam in aliquam diam. Maecenas at nibh gravida, ornare eros non, commodo ligula. Sed efficitur sollicitudin auctor. Quisque nec imperdiet purus, in ornare odio. Quisque odio felis, vestibulum et.",
    },
    {
      id: 3,
      image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
      date: "March, 2023",
      title_one: "National Endometriosis Month",
      title_two: "Endometriosis Awareness Month.",
      desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
      title_three: "#EndometriosisAwarenessMonth",
      desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
    },
    {
        id: 4,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 5,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 6,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 7,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 8,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 9,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
      {
        id: 10,
        image: "https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/333222415_516251200666244_2796704712602780276_n.jpg?stp=dst-jpg_p720x720&_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=CIjwSxX8uGYAX8VSIDQ&_nc_ht=scontent-lga3-1.xx&edm=ALdPpPkEAAAA&oh=00_AfAMWCdlR4HazUtyNuN4CFWYIsCcll3jW9WQtBJZ0Vy6Cw&oe=641253A0",
        date: "March, 2023",
        title_one: "National Endometriosis Month",
        title_two: "Endometriosis Awareness Month.",
        desc_two: "Endometriosis is a disorder in which tissue that normally lines the uterus grows outside of the uterus. Endometriosis affects an estimated 2-10% of American women between the ages of 25 and 40.",
        title_three: "#EndometriosisAwarenessMonth",
        desc_three: "Women with endometriosis are more likely to have infertility or difficulty getting pregnant. Symptoms may include excessive menstrual cramps, abnormal or heavy menstrual flow, and pain during intercourse. Fortunately, effective treatments are available.",
      },
  ]
  export default BlogData